BEGIN TRANSACTION;
CREATE TABLE IntGrounds(p_Ground INT, LongName TEXT, Country TEXT, PRIMARY KEY (p_Ground));
INSERT INTO "IntGrounds" VALUES(56293,'Adelaide Oval','Aus');
INSERT INTO "IntGrounds" VALUES(56407,'Bellerive Oval','Aus');
INSERT INTO "IntGrounds" VALUES(56326,'Berri Oval','Aus');
INSERT INTO "IntGrounds" VALUES(56336,'Brisbane Cricket Ground','Aus');
INSERT INTO "IntGrounds" VALUES(56362,'Cazaly','Aus');
INSERT INTO "IntGrounds" VALUES(56397,'Devonport Oval','Aus');
INSERT INTO "IntGrounds" VALUES(56450,'Docklands Stadium','Aus');
INSERT INTO "IntGrounds" VALUES(56322,'Eastern Oval','Aus');
INSERT INTO "IntGrounds" VALUES(56338,'Exhibition Ground','Aus');
INSERT INTO "IntGrounds" VALUES(56430,'Harrup Park','Aus');
INSERT INTO "IntGrounds" VALUES(56319,'Lavington Sports Oval','Aus');
INSERT INTO "IntGrounds" VALUES(56370,'Manuka Oval','Aus');
INSERT INTO "IntGrounds" VALUES(56441,'Melbourne Cricket Ground','Aus');
INSERT INTO "IntGrounds" VALUES(56420,'North Tasmania Cricket Association Ground','Aus');
INSERT INTO "IntGrounds" VALUES(56576,'Stadium Australia','Aus');
INSERT INTO "IntGrounds" VALUES(56544,'Sydney Cricket Ground','Aus');
INSERT INTO "IntGrounds" VALUES(56410,'Tasmania Cricket Association Ground','Aus');
INSERT INTO "IntGrounds" VALUES(56390,'TIO Stadium','Aus');
INSERT INTO "IntGrounds" VALUES(298311,'Tony Ireland Stadium','Aus');
INSERT INTO "IntGrounds" VALUES(56490,'W','Aus');
INSERT INTO "IntGrounds" VALUES(56661,'Bangabandhu National Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(737237,'Khan Shaheb Osman Ali Outer Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(56667,'Khan Shaheb Osman Ali Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(56656,'MA Aziz Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(56670,'Shaheed Chandu Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(56691,'Sheikh Abu Naser Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(236761,'Shere Bangla National Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(56689,'Sylhet International Cricket Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(56658,'Zahur Ahmed Chowdhury Stadium','Ban');
INSERT INTO "IntGrounds" VALUES(56717,'Maple Leaf North','Can');
INSERT INTO "IntGrounds" VALUES(56708,'Toronto Cricket','Can');
INSERT INTO "IntGrounds" VALUES(57296,'Bramall Lane','Eng');
INSERT INTO "IntGrounds" VALUES(56831,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(56887,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(56953,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(56825,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(57424,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(57207,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(57309,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(57351,'County Ground','Eng');
INSERT INTO "IntGrounds" VALUES(56788,'Edgbaston','Eng');
INSERT INTO "IntGrounds" VALUES(57100,'Grace Road','Eng');
INSERT INTO "IntGrounds" VALUES(57092,'Headingley','Eng');
INSERT INTO "IntGrounds" VALUES(57127,'Kennington Oval','Eng');
INSERT INTO "IntGrounds" VALUES(57129,'Lord','Eng');
INSERT INTO "IntGrounds" VALUES(57367,'Nevill Ground','Eng');
INSERT INTO "IntGrounds" VALUES(57290,'North Marine Road Ground','Eng');
INSERT INTO "IntGrounds" VALUES(57160,'Old Trafford','Eng');
INSERT INTO "IntGrounds" VALUES(56901,'Riverside Ground','Eng');
INSERT INTO "IntGrounds" VALUES(56874,'Sophia Gardens','Eng');
INSERT INTO "IntGrounds" VALUES(57347,'St Helen','Eng');
INSERT INTO "IntGrounds" VALUES(56869,'St Lawrence Ground','Eng');
INSERT INTO "IntGrounds" VALUES(57312,'The Rose Bowl','Eng');
INSERT INTO "IntGrounds" VALUES(57219,'Trent Bridge','Eng');
INSERT INTO "IntGrounds" VALUES(493864,'Mission Road Ground','HK');
INSERT INTO "IntGrounds" VALUES(58027,'Barabati Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58187,'Barkatullah Khan Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58317,'Brabourne Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58119,'Captain Roop Singh Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(343050,'Dr DY Patil Sports Academy','Ind');
INSERT INTO "IntGrounds" VALUES(58547,'Dr','Ind');
INSERT INTO "IntGrounds" VALUES(57980,'Eden Gardens','Ind');
INSERT INTO "IntGrounds" VALUES(58040,'Feroz Shah Kotla','Ind');
INSERT INTO "IntGrounds" VALUES(57871,'Gandhi Sports Complex Ground','Ind');
INSERT INTO "IntGrounds" VALUES(58164,'Gandhi Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58204,'Green Park','Ind');
INSERT INTO "IntGrounds" VALUES(58319,'Gymkhana Ground','Ind');
INSERT INTO "IntGrounds" VALUES(58150,'Holkar Cricket Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58056,'HPCA Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58537,'Indira Gandhi Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58542,'Indira Priyadarshini Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58044,'Jawaharlal Nehru Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(485865,'JSCA International Stadium Complex','Ind');
INSERT INTO "IntGrounds" VALUES(58273,'K','Ind');
INSERT INTO "IntGrounds" VALUES(58180,'Keenan Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58136,'Lal Bahadur Shastri Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(57897,'M','Ind');
INSERT INTO "IntGrounds" VALUES(58008,'MA Chidambaram Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58401,'Madhavrao Scindia Cricket Ground','Ind');
INSERT INTO "IntGrounds" VALUES(545380,'Maharashtra Cricket Association Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58373,'Moin','Ind');
INSERT INTO "IntGrounds" VALUES(58174,'Molana Azad Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58519,'Moti Bagh Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58081,'Nahar Singh Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58301,'Nehru Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58114,'Nehru Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58151,'Nehru Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58230,'Nehru Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58009,'Nehru Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58383,'Nehru Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(57991,'Punjab C','Ind');
INSERT INTO "IntGrounds" VALUES(58142,'Rajiv Gandhi International Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58516,'Reliance Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(57851,'Sardar Patel ','Ind');
INSERT INTO "IntGrounds" VALUES(57852,'Sardar Vallabhai Patel Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(377285,'Saurashtra Cricket Association Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58162,'Sawai Mansingh Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(57993,'Sector ','Ind');
INSERT INTO "IntGrounds" VALUES(58456,'Sher','Ind');
INSERT INTO "IntGrounds" VALUES(58279,'University Ground','Ind');
INSERT INTO "IntGrounds" VALUES(58479,'University Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58344,'Vidarbha C','Ind');
INSERT INTO "IntGrounds" VALUES(375326,'Vidarbha Cricket Association Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58324,'Wankhede Stadium','Ind');
INSERT INTO "IntGrounds" VALUES(58650,'Bready Cricket Club','Ire');
INSERT INTO "IntGrounds" VALUES(58604,'Castle Avenue','Ire');
INSERT INTO "IntGrounds" VALUES(58588,'Civil Service Cricket Club','Ire');
INSERT INTO "IntGrounds" VALUES(58607,'The Village','Ire');
INSERT INTO "IntGrounds" VALUES(58655,'Aga Khan Sports Club Ground','Kenya');
INSERT INTO "IntGrounds" VALUES(58661,'Gymkhana Club Ground','Kenya');
INSERT INTO "IntGrounds" VALUES(271573,'Jaffery Sports Club Ground','Kenya');
INSERT INTO "IntGrounds" VALUES(58652,'Mombasa Sports Club Ground','Kenya');
INSERT INTO "IntGrounds" VALUES(58657,'Nairobi Club Ground','Kenya');
INSERT INTO "IntGrounds" VALUES(58658,'Ruaraka Sports Club Ground','Kenya');
INSERT INTO "IntGrounds" VALUES(58659,'Simba Union Ground','Kenya');
INSERT INTO "IntGrounds" VALUES(304364,'Bayuemas Oval','Mal');
INSERT INTO "IntGrounds" VALUES(256592,'Kinrara Academy Oval','Mal');
INSERT INTO "IntGrounds" VALUES(59590,'National Cricket Stadium','Mrc');
INSERT INTO "IntGrounds" VALUES(58678,'Wanderers Cricket Ground','Nam');
INSERT INTO "IntGrounds" VALUES(58718,'Hazelaarweg','Neth');
INSERT INTO "IntGrounds" VALUES(58728,'Sportpark Thurlede','Neth');
INSERT INTO "IntGrounds" VALUES(461400,'Sportpark Westvliet','Neth');
INSERT INTO "IntGrounds" VALUES(58686,'VRA Ground','Neth');
INSERT INTO "IntGrounds" VALUES(58812,'AMI Stadium','NZ');
INSERT INTO "IntGrounds" VALUES(58895,'Basin Reserve','NZ');
INSERT INTO "IntGrounds" VALUES(444258,'Bay Oval','NZ');
INSERT INTO "IntGrounds" VALUES(58847,'Bert Sutcliffe Oval','NZ');
INSERT INTO "IntGrounds" VALUES(58822,'Carisbrook','NZ');
INSERT INTO "IntGrounds" VALUES(441704,'Cobham Oval ','NZ');
INSERT INTO "IntGrounds" VALUES(58792,'Eden Park','NZ');
INSERT INTO "IntGrounds" VALUES(58810,'Hagley Oval','NZ');
INSERT INTO "IntGrounds" VALUES(58857,'McLean Park','NZ');
INSERT INTO "IntGrounds" VALUES(58879,'Owen Delany Park','NZ');
INSERT INTO "IntGrounds" VALUES(58865,'Pukekura Park','NZ');
INSERT INTO "IntGrounds" VALUES(58919,'Queenstown Events Centre','NZ');
INSERT INTO "IntGrounds" VALUES(424917,'Saxton Oval','NZ');
INSERT INTO "IntGrounds" VALUES(58831,'Seddon Park','NZ');
INSERT INTO "IntGrounds" VALUES(58827,'University Oval','NZ');
INSERT INTO "IntGrounds" VALUES(58899,'Westpac Stadium','NZ');
INSERT INTO "IntGrounds" VALUES(58988,'Arbab Niaz Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58995,'Ayub National Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58965,'Bagh','Pak');
INSERT INTO "IntGrounds" VALUES(58921,'Bahawal Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58996,'Bugti Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58967,'Gaddafi Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58982,'Ibn','Pak');
INSERT INTO "IntGrounds" VALUES(58927,'Iqbal Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58930,'Jinnah Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(59018,'Jinnah Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58986,'Multan Cricket Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58956,'National Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58936,'Niaz Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58991,'Peshawar Club Ground','Pak');
INSERT INTO "IntGrounds" VALUES(59004,'Pindi Club Ground','Pak');
INSERT INTO "IntGrounds" VALUES(59006,'Rawalpindi Cricket Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(59016,'Sheikhupura Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(58950,'Southend Club Cricket Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(59014,'Sports Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(59011,'Zafar Ali Stadium','Pak');
INSERT INTO "IntGrounds" VALUES(59258,'Cambusdoon New Ground','Scot');
INSERT INTO "IntGrounds" VALUES(59269,'Grange Cricket Club','Scot');
INSERT INTO "IntGrounds" VALUES(59255,'Mannofield Park','Scot');
INSERT INTO "IntGrounds" VALUES(59275,'Titwood','Scot');
INSERT INTO "IntGrounds" VALUES(59387,'Kallang Ground','Sin');
INSERT INTO "IntGrounds" VALUES(59389,'Singapore Cricket Club','Sin');
INSERT INTO "IntGrounds" VALUES(59147,'Boland Park','SA');
INSERT INTO "IntGrounds" VALUES(59098,'Buffalo Park','SA');
INSERT INTO "IntGrounds" VALUES(59151,'City Oval','SA');
INSERT INTO "IntGrounds" VALUES(59135,'Diamond Oval','SA');
INSERT INTO "IntGrounds" VALUES(59112,'Ellis Park','SA');
INSERT INTO "IntGrounds" VALUES(59089,'Kingsmead','SA');
INSERT INTO "IntGrounds" VALUES(59090,'Lord','SA');
INSERT INTO "IntGrounds" VALUES(59042,'Mangaung Oval','SA');
INSERT INTO "IntGrounds" VALUES(463140,'Moses Mabhida Stadium','SA');
INSERT INTO "IntGrounds" VALUES(59068,'Newlands','SA');
INSERT INTO "IntGrounds" VALUES(59122,'Old Wanderers','SA');
INSERT INTO "IntGrounds" VALUES(59172,'Senwes Park','SA');
INSERT INTO "IntGrounds" VALUES(59159,'St George','SA');
INSERT INTO "IntGrounds" VALUES(59079,'SuperSport Park','SA');
INSERT INTO "IntGrounds" VALUES(59120,'The Wanderers Stadium','SA');
INSERT INTO "IntGrounds" VALUES(59039,'Willowmoore Park','SA');
INSERT INTO "IntGrounds" VALUES(59329,'Asgiriya Stadium','SL');
INSERT INTO "IntGrounds" VALUES(59294,'Colombo Cricket Club Ground','SL');
INSERT INTO "IntGrounds" VALUES(59325,'Galle International Stadium','SL');
INSERT INTO "IntGrounds" VALUES(434210,'Mahinda Rajapaksa International Cricket Stadium','SL');
INSERT INTO "IntGrounds" VALUES(59303,'P Sara Oval','SL');
INSERT INTO "IntGrounds" VALUES(434211,'Pallekele International Cricket Stadium','SL');
INSERT INTO "IntGrounds" VALUES(59306,'R','SL');
INSERT INTO "IntGrounds" VALUES(59368,'Rangiri Dambulla International Stadium','SL');
INSERT INTO "IntGrounds" VALUES(59308,'Sinhalese Sports Club Ground','SL');
INSERT INTO "IntGrounds" VALUES(59350,'Tyronne Fernando Stadium','SL');
INSERT INTO "IntGrounds" VALUES(392627,'Dubai International Cricket Stadium','UAE');
INSERT INTO "IntGrounds" VALUES(481147,'ICC Academy','UAE');
INSERT INTO "IntGrounds" VALUES(59392,'Sharjah Cricket Stadium','UAE');
INSERT INTO "IntGrounds" VALUES(59396,'Sheikh Zayed Stadium','UAE');
INSERT INTO "IntGrounds" VALUES(378262,'Central Broward Regional Park Stadium Turf Ground','USA');
INSERT INTO "IntGrounds" VALUES(59417,'Albion Sports Complex','WI');
INSERT INTO "IntGrounds" VALUES(59495,'Antigua Recreation Ground','WI');
INSERT INTO "IntGrounds" VALUES(59463,'Arnos Vale Ground','WI');
INSERT INTO "IntGrounds" VALUES(59518,'Beausejour Cricket Ground','WI');
INSERT INTO "IntGrounds" VALUES(59447,'Bourda','WI');
INSERT INTO "IntGrounds" VALUES(59429,'Kensington Oval','WI');
INSERT INTO "IntGrounds" VALUES(59434,'Mindoo Phillip Park','WI');
INSERT INTO "IntGrounds" VALUES(59490,'National Cricket Stadium','WI');
INSERT INTO "IntGrounds" VALUES(208544,'Providence Stadium','WI');
INSERT INTO "IntGrounds" VALUES(59492,'Queen','WI');
INSERT INTO "IntGrounds" VALUES(59475,'Queen','WI');
INSERT INTO "IntGrounds" VALUES(59458,'Sabina Park','WI');
INSERT INTO "IntGrounds" VALUES(208543,'Sir Vivian Richards Stadium','WI');
INSERT INTO "IntGrounds" VALUES(59421,'Warner Park','WI');
INSERT INTO "IntGrounds" VALUES(59480,'Windsor Park','WI');
INSERT INTO "IntGrounds" VALUES(59534,'Bulawayo Athletic Club','Zim');
INSERT INTO "IntGrounds" VALUES(59545,'Harare Sports Club','Zim');
INSERT INTO "IntGrounds" VALUES(59560,'Kwekwe Sports Club','Zim');
INSERT INTO "IntGrounds" VALUES(59537,'Queens Sports Club','Zim');
COMMIT;